export { default as MainSlider } from "./MainSlider";
export type { MainSlideType } from "./MainSlider";
export { default as TopSlider } from "./TopSlider";
export { default as NoveltySlider } from "./NoveltySlider";
export { default as JackpotSlider } from "./JackpotSlider";
export { default as ProviderSlider } from "./ProviderSlider";
export { default as LiveSlider } from "./LiveSlider";
export { default as TableSlider } from "./TableSlider";
export { default as BonusSlider } from "./BonusSlider";
export { default as TournamentSlider } from "./TournamentSlider";
